// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj2wASGqhZfbwfJpnP6Jl8gxkagWf-4nw',
    appId: '1:603590972566:web:7e9c5c2ddb5da980831eb7',
    messagingSenderId: '603590972566',
    projectId: 'servicoentrega-f9127',
    authDomain: 'servicoentrega-f9127.firebaseapp.com',
    databaseURL: 'https://servicoentrega-f9127-default-rtdb.firebaseio.com',
    storageBucket: 'servicoentrega-f9127.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCnVOQjO-02lfHJg1_6wQPC7252t5gu3A',
    appId: '1:603590972566:android:11c67baca809b1f0831eb7',
    messagingSenderId: '603590972566',
    projectId: 'servicoentrega-f9127',
    databaseURL: 'https://servicoentrega-f9127-default-rtdb.firebaseio.com',
    storageBucket: 'servicoentrega-f9127.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDESJTKxAuCsHul0OBKdj9nE36dkcg5vn8',
    appId: '1:603590972566:ios:73585f4c15980969831eb7',
    messagingSenderId: '603590972566',
    projectId: 'servicoentrega-f9127',
    databaseURL: 'https://servicoentrega-f9127-default-rtdb.firebaseio.com',
    storageBucket: 'servicoentrega-f9127.appspot.com',
    iosClientId: '603590972566-3rpgtl5ug2ngctikcjsukk7se1668hlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.attPedidos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDESJTKxAuCsHul0OBKdj9nE36dkcg5vn8',
    appId: '1:603590972566:ios:73585f4c15980969831eb7',
    messagingSenderId: '603590972566',
    projectId: 'servicoentrega-f9127',
    databaseURL: 'https://servicoentrega-f9127-default-rtdb.firebaseio.com',
    storageBucket: 'servicoentrega-f9127.appspot.com',
    iosClientId: '603590972566-3rpgtl5ug2ngctikcjsukk7se1668hlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.attPedidos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj2wASGqhZfbwfJpnP6Jl8gxkagWf-4nw',
    appId: '1:603590972566:web:783101973b7eb1c5831eb7',
    messagingSenderId: '603590972566',
    projectId: 'servicoentrega-f9127',
    authDomain: 'servicoentrega-f9127.firebaseapp.com',
    databaseURL: 'https://servicoentrega-f9127-default-rtdb.firebaseio.com',
    storageBucket: 'servicoentrega-f9127.appspot.com',
  );

}